#include "visualization.h"

#include <errno.h>
#include <mpi.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <sys/types.h>

// TODO(ruan): generated by clunker, i have not reviewd
typedef struct Dot_Buffer Dot_Buffer;
struct Dot_Buffer {
	char *data;
	u64 size;
	u64 capacity;
};

static void dot_buffer_reserve(Dot_Buffer *buffer, u64 additional) {
	u64 needed = buffer->size + additional;
	if (needed <= buffer->capacity) return;

	u64 new_capacity = buffer->capacity ? buffer->capacity * 2 : KILOBYTE(4);
	while (new_capacity < needed) new_capacity *= 2;
	char *new_data = (char *)realloc(buffer->data, new_capacity);
	if (!new_data) {
		ERROR("Failed to grow DOT buffer");
		ABORT();
	}
	buffer->data = new_data;
	buffer->capacity = new_capacity;
}

static void dot_buffer_appendf(Dot_Buffer *buffer, const char *format, ...) {
	while (true) {
		va_list args;
		va_start(args, format);
		i32 available = buffer->capacity > buffer->size ? (i32)(buffer->capacity - buffer->size) : 0;
		i32 written = vsnprintf(buffer->data ? buffer->data + buffer->size : 0, available, format, args);
		va_end(args);
		if (written < 0) {
			ERROR("Failed to format DOT buffer");
			ABORT();
		}
		if ((u64)written < (u64)available) {
			buffer->size += (u64)written;
			return;
		}
		dot_buffer_reserve(buffer, (u64)written + 1);
	}
}

static void dot_buffer_free(Dot_Buffer *buffer) {
	free(buffer->data);
	*buffer = (Dot_Buffer){0};
}

static void ensure_output_dir(Worker_State *ws, const char *output_dir) {
	if (ws->rank == 0) {
		if (mkdir(output_dir, 0777) != 0 && errno != EEXIST) {
			ERROR("Failed to create DOT output directory %s", output_dir);
			worker_abort(ws, 1);
		}
	}
	MPI_Barrier(MPI_COMM_WORLD);
}

static FILE *open_dot_file(Worker_State *ws, const char *output_dir, const char *name) {
	char path[1024];
	snprintf(path, sizeof(path), "%s/%s", output_dir, name);
	FILE *file = fopen(path, "w");
	if (!file) {
		ERROR("Rank %d: failed to open DOT file %s", ws->rank, path);
		worker_abort(ws, 1);
	}
	return file;
}

static void gather_and_write_global_dot(Worker_State *ws, const char *output_dir, const char *name, const char *header, const char *footer, const Dot_Buffer *local_lines) {
	i32 local_size = (i32)local_lines->size;
	i32 *counts = 0;
	i32 *displs = 0;
	char *global_lines = 0;

	if (ws->rank == 0) {
		counts = (i32 *)malloc((u64)ws->rank_size * sizeof(i32));
		displs = (i32 *)malloc((u64)ws->rank_size * sizeof(i32));
		if (!counts || !displs) {
			ERROR("Failed to allocate DOT gather metadata");
			worker_abort(ws, 1);
		}
	}

	MPI_Gather(&local_size, 1, MPI_INT, counts, 1, MPI_INT, 0, MPI_COMM_WORLD);

	i32 total_size = 0;
	if (ws->rank == 0) {
		for (i32 pe = 0; pe < ws->rank_size; ++pe) {
			displs[pe] = total_size;
			total_size += counts[pe];
		}
		global_lines = total_size ? (char *)malloc((u64)total_size) : 0;
		if (total_size && !global_lines) {
			ERROR("Failed to allocate global DOT buffer");
			worker_abort(ws, 1);
		}
	}

	MPI_Gatherv(local_lines->data, local_size, MPI_BYTE, global_lines, counts, displs, MPI_BYTE, 0, MPI_COMM_WORLD);

	if (ws->rank == 0) {
		FILE *file = open_dot_file(ws, output_dir, name);
		fputs(header, file);
		if (total_size) fwrite(global_lines, 1, (u64)total_size, file);
		fputs(footer, file);
		fclose(file);
		free(global_lines);
		free(counts);
		free(displs);
	}
}

static u64 vertex_local_host(u64 vertex, Worker_State *ws) {
	return vertex / (u64)ws->rank_size;
}

static i32 vertex_owner_host(u64 vertex, Worker_State *ws) {
	return (i32)(vertex % (u64)ws->rank_size);
}

static void append_vertex_dot_line(Dot_Buffer *buffer, Worker_State *ws, u64 vertex) {
	dot_buffer_appendf(buffer, "  %llu [label=\"v%llu\\npe=%d local=%llu\"];\n",
			(unsigned long long)vertex,
			(unsigned long long)vertex,
			vertex_owner_host(vertex, ws),
			(unsigned long long)vertex_local_host(vertex, ws));
}

static void append_tuple_dot_lines(Dot_Buffer *buffer, Worker_State *ws, const Packed_Edge *edges, const f32 *weights, u64 edge_count) {
	for (u64 edge_idx = 0; edge_idx < edge_count; ++edge_idx) {
		append_vertex_dot_line(buffer, ws, edges[edge_idx].v0);
		append_vertex_dot_line(buffer, ws, edges[edge_idx].v1);
		dot_buffer_appendf(buffer, "  %llu -- %llu [label=\"%.6g\"];\n",
				(unsigned long long)edges[edge_idx].v0,
				(unsigned long long)edges[edge_idx].v1,
				(double)weights[edge_idx]);
	}
}

void tuple_graph_write_dot_files(Worker_State *ws, const Tuple_Graph *tg, const char *output_dir) {
	ensure_output_dir(ws, output_dir);

	size_t edge_bytes = (size_t)tg->edges_size * sizeof(Packed_Edge);
	size_t weight_bytes = (size_t)tg->edges_size * sizeof(f32);
	Packed_Edge *host_edges = edge_bytes ? (Packed_Edge *)malloc(edge_bytes) : 0;
	f32 *host_weights = weight_bytes ? (f32 *)malloc(weight_bytes) : 0;
	if ((edge_bytes && !host_edges) || (weight_bytes && !host_weights)) {
		ERROR("Failed to allocate host tuple DOT buffers");
		worker_abort(ws, 1);
	}

	if (edge_bytes) CHECK_CUDA(cudaMemcpy(host_edges, tg->edges, edge_bytes, cudaMemcpyDeviceToHost));
	if (weight_bytes) CHECK_CUDA(cudaMemcpy(host_weights, tg->weights, weight_bytes, cudaMemcpyDeviceToHost));

	Dot_Buffer lines = {0};
	append_tuple_dot_lines(&lines, ws, host_edges, host_weights, tg->edges_size);

	char local_name[128];
	snprintf(local_name, sizeof(local_name), "tuple_pe_%03d.dot", ws->rank);
	FILE *local_file = open_dot_file(ws, output_dir, local_name);
	fprintf(local_file, "graph tuple_pe_%d {\n", ws->rank);
	if (lines.size) fwrite(lines.data, 1, lines.size, local_file);
	fputs("}\n", local_file);
	fclose(local_file);

	gather_and_write_global_dot(ws, output_dir, "tuple_global.dot", "graph tuple_global {\n", "}\n", &lines);

	dot_buffer_free(&lines);
	free(host_edges);
	free(host_weights);
}

static void append_oned_dot_lines(Dot_Buffer *buffer, Worker_State *ws, const u64 *rowstarts, const u64 *column, const f32 *weights, u64 nlocalverts) {
	for (u64 local_vertex = 0; local_vertex < nlocalverts; ++local_vertex) {
		u64 src = local_vertex * (u64)ws->rank_size + (u64)ws->rank;
		append_vertex_dot_line(buffer, ws, src);
		for (u64 edge_idx = rowstarts[local_vertex]; edge_idx < rowstarts[local_vertex + 1]; ++edge_idx) {
			append_vertex_dot_line(buffer, ws, column[edge_idx]);
			dot_buffer_appendf(buffer, "  %llu -> %llu [label=\"%.6g\"];\n",
					(unsigned long long)src,
					(unsigned long long)column[edge_idx],
					(double)weights[edge_idx]);
		}
	}
}

void oned_graph_write_dot_files(Worker_State *ws, const Oned_Graph *g, const char *output_dir) {
	ensure_output_dir(ws, output_dir);

	size_t rowstart_bytes = (size_t)(g->nlocalverts + 1) * sizeof(u64);
	size_t column_bytes = (size_t)g->nlocaledges * sizeof(u64);
	size_t weight_bytes = (size_t)g->nlocaledges * sizeof(f32);
	u64 *host_rowstarts = rowstart_bytes ? (u64 *)malloc(rowstart_bytes) : 0;
	u64 *host_column = column_bytes ? (u64 *)malloc(column_bytes) : 0;
	f32 *host_weights = weight_bytes ? (f32 *)malloc(weight_bytes) : 0;
	if ((rowstart_bytes && !host_rowstarts) || (column_bytes && !host_column) || (weight_bytes && !host_weights)) {
		ERROR("Failed to allocate host Oned_Graph DOT buffers");
		worker_abort(ws, 1);
	}

	if (rowstart_bytes) CHECK_CUDA(cudaMemcpy(host_rowstarts, g->rowstarts, rowstart_bytes, cudaMemcpyDeviceToHost));
	if (column_bytes) CHECK_CUDA(cudaMemcpy(host_column, g->column, column_bytes, cudaMemcpyDeviceToHost));
	if (weight_bytes) CHECK_CUDA(cudaMemcpy(host_weights, g->weights, weight_bytes, cudaMemcpyDeviceToHost));

	Dot_Buffer lines = {0};
	append_oned_dot_lines(&lines, ws, host_rowstarts, host_column, host_weights, g->nlocalverts);

	char local_name[128];
	snprintf(local_name, sizeof(local_name), "oned_pe_%03d.dot", ws->rank);
	FILE *local_file = open_dot_file(ws, output_dir, local_name);
	fprintf(local_file, "digraph oned_pe_%d {\n", ws->rank);
	if (lines.size) fwrite(lines.data, 1, lines.size, local_file);
	fputs("}\n", local_file);
	fclose(local_file);

	gather_and_write_global_dot(ws, output_dir, "oned_global.dot", "digraph oned_global {\n", "}\n", &lines);

	dot_buffer_free(&lines);
	free(host_rowstarts);
	free(host_column);
	free(host_weights);
}
